# Generated by Django 5.1.3 on 2025-07-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalonAIApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('session_id', models.CharField(max_length=128)),
                ('query', models.TextField()),
                ('agent_trace', models.JSONField()),
                ('final_output', models.JSONField()),
                ('car_profile_snapshot', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
